### ISSUE TITLE
Failure with getAllUsers() on pyral 1.3.1 and Python 3.6.2

### ISSUE THREAD

**Issue by pgacv2** [RallyTools/RallyRestToolkitForPython#125]
Code to reproduce:
```
import pyral
rally = pyral.Rally(apikey='*****')
users = rally.getAllUsers()
```

Result:
```
"C:\Program Files\Python36\python.exe" C:/Users/me/.PyCharmCE2017.1/config/scratches/scratch_7.py
Retrying the page_urls for the page group startIndexes: 501 -> 1001
Retrying the page_urls for the page group startIndexes: 501 -> 1001
Traceback (most recent call last):
Retrying the page_urls for the page group startIndexes: 501 -> 1001
  File "C:/Users/me/.PyCharmCE2017.1/config/scratches/scratch_7.py", line 4, in <module>
    users = rally.getAllUsers()
  File "C:\Program Files\Python36\lib\site-packages\pyral\restapi.py", line 633, in getAllUsers
    users = [user for user in response]
  File "C:\Program Files\Python36\lib\site-packages\pyral\restapi.py", line 633, in <listcomp>
    users = [user for user in response]
  File "C:\Program Files\Python36\lib\site-packages\pyral\rallyresp.py", line 311, in __next__
    self._page[:]  = self.__retrieveNextPage()
  File "C:\Program Files\Python36\lib\site-packages\pyral\rallyresp.py", line 408, in __retrieveNextPage
    chapter = self.__retrievePages()
  File "C:\Program Files\Python36\lib\site-packages\pyral\rallyresp.py", line 476, in __retrievePages
    raise RallyResponseError("Unable to retrieve %d chunks of data" % num_threads)
pyral.rallyresp.RallyResponseError: Unable to retrieve 2 chunks of data

Process finished with exit code 1
```

**Comment by pgacv2** [comment]
Sorry for the late response. Yes, this is still reproducible across retries on 1.3.1 and 1.4.0. Let me know if I should open a new issue.
