### ISSUE TITLE
StopIteration at connection

### ISSUE THREAD

**Issue by boetnet** [RallyTools/RallyRestToolkitForPython#153]
Hi,

I am simply trying to execute the following script:

```
from pyral import Rally
rally = Rally(server="rally1.rallydev.com", user="xxxxx@xxxx.com", password="xxxxxx")
```

And I got the following error raised:

```
Traceback (most recent call last):
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\xxxxx\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\xxxxx\OneDrive - moodys.com\Private\Dev\Python\RallyExtractor\test.py", line 2, in <module>
    rally = Rally(server="rally1.rallydev.com", user="xxxxxx@xxxxxx.com", password="xxxxxxx")
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyral\restapi.py", line 259, in __init__
    self.contextHelper.check(self.server, wksp, proj, self.isolated_workspace)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyral\context.py", line 175, in check
    self._getDefaults(user_response)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyral\context.py", line 429, in _getDefaults
    user = user_response.next()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyral\rallyresp.py", line 290, in next
    return self.__next__()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyral\rallyresp.py", line 304, in __next__
    raise StopIteration
StopIteration
```

I got a valid message when I execute the code described in this ticket [#38](https://github.com/RallyTools/RallyRestToolkitForPython/issues/38). Ticket [#77](https://github.com/RallyTools/RallyRestToolkitForPython/issues/77) does not really help.

I got a valid response when I contact https://rally1.rallydev.com/slm/webservice/v2.0/User?fetch=true with postman.

```
>>> pyral.__version__
(1, 4, 2)
```

I am kinda stuck.

Thank you in advance for your help.

**Comment by klehman-rally** [comment]
This _may_ be due to not having a default workspace and project for the user specified.  Try a similar Rally(...) instantiation call  using a workspace and project value that you know your user has at least read access to.  If the exact same 'StopIteration'  exception gets raised, post that back here and I'll look into this issue further.

**Comment by klehman-rally** [comment]
There are two workarounds to this that are supported.
1) Either you or your subscription admin can set up your account to have a default workspace and default project.
2) Supply a workspace and project value to which you have at least Viewer access.
