### ISSUE TITLE
Pyral: AttributeError: PortfolioItem instance has no attribute: '_generateRallyCompliance__collection_ref_for_UserStories'

### ISSUE THREAD

**Issue by mikkiahuja** [RallyTools/RallyRestToolkitForPython#190]
I have a requirement to fetch all user stories under a feature for which i have written a code outlined below. The feature object has an attribute __collection_ref_for_UserStories which gives the collection URL to get details of all US but on accessing the attribute it gives an attribute error.

Please guide how can i access dunder (__) attributes.

`import rallyReportglobalRallyObject

class generateRallyCompliance():
    def __init__(self):
        if rallyReportglobalRallyObject.rally is None:
            rallyReportglobalRallyObject.createGlobalRallyObject()
            self.rally = rallyReportglobalRallyObject.rally
        else:
            self.rally = rallyReportglobalRallyObject.rally

    def getFeatureLevelDetail(self):
        feature = self.rally.get('PortfolioItem/Feature',fetch=True,pagesize=200)
        for f in feature:
            print(f.attributes())
            print(f.__collection_ref_for_UserStories)

if __name__ == '__main__':
    co=generateRallyCompliance()
    co.getFeatureLevelDetail()`

**Output**: ['AcceptedLeafStoryCount', 'AcceptedLeafStoryPlanEstimateTotal', 'ActualEndDate', 'ActualStartDate', 'Archived', 'Attachments', 'Blocked', 'BlockedReason', 'Blocker', 'Changesets', 'Connections', 'CreatedBy', 'CreationDate', 'Description', 'DirectChildrenCount', 'Discussion', 'DisplayColor', 'DragAndDropRank', 'Expedite', 'FormattedID', 'InvestmentCategory', 'Investments', 'JobSize', 'LastRollupDate', 'LastUpdateDate', 'LateChildCount', 'LatestDiscussionAgeInMinutes', 'LeafStoryCount', 'LeafStoryPlanEstimateTotal', 'Milestones', 'Name', 'Notes', 'ObjectID', 'ObjectUUID', 'Owner', 'Parent', 'PercentDoneByStoryCount', 'PercentDoneByStoryPlanEstimate', 'PlannedEndDate', 'PlannedStartDate', 'PortfolioItemType', 'PortfolioItemTypeName', 'Predecessors', 'PreliminaryEstimate', 'PreliminaryEstimateValue', 'Project', 'RROEValue', 'Ready', 'Recycled', 'RefinedEstimate', 'Release', 'RiskScore', 'State', 'StateChangedDate', 'Subscription', 'Successors', 'Tags', 'TimeCriticality', 'UnEstimatedLeafStoryCount', 'UserBusinessValue', 'ValueScore', 'VersionId', 'WSJFScore', 'Workspace', '_CreatedAt', '__collection_ref_for_Collaborators', '__collection_ref_for_RevisionHistory', '__collection_ref_for_Risks', **'__collection_ref_for_UserStories',** '_hydrated', '_ref', '_refObjectUUID', '_type', 'c_ALTPortfolioKanban', 'c_AMLKanbanState', 'c_AOINReference', 'c_ARDeliveryManager', 'c_ARPMDirector', 'c_AbovetheLine', 'c_AcceptanceCriteria', 'c_AccomplishmentType', 'c_ActualEndPI', 'c_ActualStartPI', 'c_AnnualCostSavings', 'c_AnnualIncrementalLoans', 'c_AnnualIncrementalNAANCA', 'c_AnnualIncrementalSpend', 'c_ApplicationName', 'c_ApprovedFunding', 'c_Architect', 'c_Area', 'c_AutomationTool', 'c_BIDEpicApprover', 'c_BIDInitiativeID', 'c_BenefittingBusinessUnit', 'c_BuildComplexity', 'c_BusinessDriverInitiative', 'c_BusinessEPICID', 'c_BusinessInitiative', 'c_BusinessRequestedEndDate', 'c_BusinessUnit', 'c_BusinessValueWSJF', 'c_CABReviewStatus', 'c_CABSasinet', 'c_CABUpdateonTestStatus', 'c_CCCPortfolioKanbanState', 'c_CCCProgramState', 'c_CCCValueStream', 'c_CFRKanbanState', 'c_CFRSegment', 'c_CFRUUWFSegment', 'c_COD', 'c_CalculatedEndPI', 'c_CalculatedEnvisionEndPI', 'c_CalculatedEnvsionStartPI', 'c_CalculatedEstimate', 'c_CalculatedEstimateValue', 'c_CalculatedStartPI', 'c_CapabilityType', 'c_CardProductTeam', 'c_CarryOver', 'c_CertificationKanban', 'c_ChangeRecordID', 'c_Compliance', 'c_ComplianceContact', 'c_CompliancePartner', 'c_Components', 'c_Countries', 'c_Country', 'c_Custom1TLMThirdPartyLifecycleMgmt', 'c_Custom2FunctionalArchitectureReview', 'c_Custom3TechnicalArchitectureReview', 'c_CustomDate1', 'c_CustomDate2', 'c_CustomField1', 'c_CustomField2', 'c_CustomField3', 'c_CustomField4', 'c_CustomField5', 'c_DBImpact', 'c_Deliverable', 'c_DeliveryManager', 'c_Demand', 'c_Department', 'c_Dependency', 'c_DevEndPI', 'c_DevStartPI', 'c_Developers', 'c_DirectCustomerImpact', 'c_Director', 'c_E2EDeliveryManagerName', 'c_E2EDeliveryManagerNameFeature', 'c_EAEpic', 'c_EIR', 'c_ERStatus', 'c_ERType', 'c_Enabler', 'c_EnablerTechDebt', 'c_EngagementState', 'c_EnterpriseApprovalEA', 'c_EnterpriseOutcome', 'c_EnvisionEndPI', 'c_EnvisionStartPI', 'c_EstimatedValue', 'c_ExternalID', 'c_FeatureMaturity', 'c_FeatureMaturityInitiative', 'c_FeatureReadinessKanbanNolongeruse', 'c_FeatureReadyState', 'c_FeatureStage', 'c_FeedbackLoop', 'c_FundingLOB', 'c_FundingStatus', 'c_FundingStatusInitiative', 'c_GARCapability', 'c_GARDemoNotes', 'c_GARDemoStatus', 'c_GCSTKanbanFeature', 'c_GCSTKanbanInitiativenolongerused', 'c_GRKanbanStateNolongerused', 'c_GRKanbanStateNotesNolongerused', 'c_GTOSState', 'c_GlobestarArchitect', 'c_Grooming', 'c_HighLevelEstimate', 'c_HorizonLevel', 'c_ISLImpacts', 'c_ImpactedChannels', 'c_ImpactedJourneys', 'c_ImpactedPlatforms', 'c_ImpactedPorticoCardProducts', 'c_ImpactedPorticoTeams', 'c_ImpactedSystem', 'c_ImpactedSystems', 'c_ImplementationDate', 'c_ImplementationNotes', 'c_ImplementationSignoff', 'c_InitiativeOwnerName', 'c_IntakeCompliance', 'c_IntakeGoal', 'c_IntakeHowUrgent', 'c_IntakeLineofBusiness', 'c_IntakeLoE', 'c_IntakeLoans', 'c_IntakeNPS', 'c_IntakeRegulatory', 'c_IntakeRequestID', 'c_IntakeRisk', 'c_IntakeScope', 'c_IntakeSubmitter', 'c_InvestmentID', 'c_JIRAURL', 'c_JapanReviewed', 'c_JobSizeWSJF', 'c_LOB2DONOTREOPEN', 'c_LOBBifurcation', 'c_LOBCriticality', 'c_LOBRanking', 'c_LOBTheme', 'c_LPImpactedTeams', 'c_LPMKeyResults', 'c_LPMObjectives', 'c_LPMTeam', 'c_LPProductFamily', 'c_LeadARPM', 'c_LegalRegAssessment', 'c_Lifecycle', 'c_LineofBusiness', 'c_MLRBRTBIndicator', 'c_MOSCOWPriority', 'c_MOSCOWRank', 'c_MYCAImpacts', 'c_ManualUPH', 'c_Market', 'c_MarketImpacted', 'c_MicroServiceName', 'c_Microservice', 'c_MinViableProduct', 'c_MinimumViableProduct', 'c_MonthlyFinancialImpact', 'c_NCLCustom1', 'c_NCLProduct', 'c_NEMOKanbanState', 'c_Nolongerbeingused', 'c_ObligationDate', 'c_ObligationType', 'c_OnHold', 'c_Organization', 'c_OutcomeNumber', 'c_PIFinishName', 'c_PIKanbanState', 'c_PIMultiSelect', 'c_PIStage', 'c_PIStageConfidence', 'c_PIStartName', 'c_PMTMasterProjectID', 'c_PMTSubProjectID', 'c_PONote', 'c_PSHKanbanStateNolongerused', 'c_Parm', 'c_ParmDate', 'c_PlanningCycle', 'c_Platform', 'c_PortfolioFeatureStageCMT', 'c_PortfolioKanbanStateNolongerused', 'c_PortfolioKanbanXPA', 'c_PorticoARTs', 'c_PorticoCalculatedBusinessValue', 'c_PorticoNonRisk', 'c_PrimaryFeatureWorkType', 'c_PrimaryFeatureWorkTypeAttestation', 'c_PrimaryRevenueUnit', 'c_PrimaryScrumTeam', 'c_Priority', 'c_PriorityNo', 'c_PriorityTier', 'c_ProcessType', 'c_Product', 'c_ProductAnalyst', 'c_ProductCategory', 'c_ProductDirector', 'c_ProductManager', 'c_ProductOwner', 'c_ProductTeam', 'c_ProductType', 'c_ProgramManager', 'c_ProjectMasterDC', 'c_ProjectSubDC', 'c_ProjectURLs', 'c_RABApprovalCertificate', 'c_RABApprovalDate', 'c_RABApprovedBy', 'c_RABApproverRequired', 'c_RABJapanImpact', 'c_RABNotes', 'c_RABReviewStatus', 'c_RABReviewStatusOLD', 'c_RCM', 'c_RGFAllocation', 'c_RROEWSJF', 'c_RTE', 'c_Ranking', 'c_Region', 'c_ReleaseContainer', 'c_RemittanceCapabilityCategory', 'c_RiskCategory', 'c_RiskOwnerROAM', 'c_RoadmapTransformationSubCategory', 'c_SAFeKanbanState', 'c_SARCategory', 'c_SREDIndicator', 'c_SSR', 'c_SchedulingChangeCMR', 'c_SolutionArchitectName', 'c_SolutionPI', 'c_Stakeholders', 'c_StatedBusinessValue', 'c_StrategicPillar', 'c_SubmitforImplementationCAB', 'c_SubmittoCABold', 'c_SubmittoRAB', 'c_SuccessMetricCalculation1', 'c_SuccessMetricCalculation2', 'c_SuccessMetricDescription1', 'c_SuccessMetricDescription2', 'c_SuccessMetricName1', 'c_SuccessMetricName2', 'c_SupportTeam', 'c_SystemEngagementRequest', 'c_Systems', 'c_TBD', 'c_TargetGoLiveDate', 'c_Teams', 'c_TechStack', 'c_TestComplexity', 'c_TestSupportSystems', 'c_TimeCriticalityWSJF', 'c_Tranche', 'c_USLTDevImpacts', 'c_USLTTestSupportOnly', 'c_VPSponsor', 'c_VirtualReleaseID', 'c_WorkQueueSLA', 'c_ZTR2JS', 'c_tobereuseddecimal2', 'oid', 'typePath']

Traceback (most recent call last): File "", line 1, in File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile pydev_imports.execfile(filename, global_vars, local_vars) # execute the script File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "/Users/mahuj20/Documents/Python/AiDaRallyReports/aidaRallyReports.py", line 21, in co.getFeatureLevelDetail() File "/Users/mahuj20/Documents/Python/AiDaRallyReports/aidaRallyReports.py", line 16, in getFeatureLevelDetail print(f.__collection_ref_for_UserStories) File "/usr/local/lib/python3.9/site-packages/pyral/entity.py", line 189, in getattr raise AttributeError(description) AttributeError: PortfolioItem instance has no attribute: '_generateRallyCompliance__collection_ref_for_UserStories'

**Comment by mikkiahuja** [comment]
@klehman-rally : Please address my query.
