### ISSUE TITLE
AttributeError: 'RallyRESTResponse' object has no attribute '_served

### ISSUE THREAD

**Issue by acromo1** [RallyTools/RallyRestToolkitForPython#36]
Traceback (most recent call last):
  File "./feature_rollup_spreadsheet.py", line 729, in <module>
    sys.exit(main())
  File "./feature_rollup_spreadsheet.py", line 645, in main
    for testcase in testcases:
  File "/usr/lib/python2.6/site-packages/pyral/rallyresp.py", line 255, in next
    if (self._served >= self._servable) or (self._limit and self._served >= self._limit):
AttributeError: 'RallyRESTResponse' object has no attribute '_served'

**Comment by anushreeapk** [comment]
I have been getting the same error. Can you tell me how to resolve it ?
