### ISSUE TITLE
StopIteration error after Rally Upgrade and switch to LDAP authentication

### ISSUE THREAD

**Issue by stumpjumper** [RallyTools/RallyRestToolkitForPython#38]
Hello.  I have a few scripts using PyRal that worked fine until the IT department took over management of Rally.  The Rally database used did not change, but we moved from On-Premises 2014.1 to 2014.2 and switched to using the Rally LDAP module for authentication.  Below is a traceback showing the error.  This occurs on both a Mac OS X 10.9 and Red Hat 6 Linux system.

Thank you for your time.

Version Info
pyral.__version__
(1, 1, 0)

Rally On-Premises 2014.2
Using Rally LDAP module for authentication

Mac OS 10.9.5
Python 2.7.8 (default, Jul 13 2014, 17:11:32) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
py27-requests @2.4.0_0 (via MacPorts)

Red Hat Enterprise Linux Workstation release 6.3 (Santiago)
Python 2.6.6 (r266:84292, Aug 28 2012, 10:55:56) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
requests v2.3.0

Mac OS X traceback
(Note sure why the Mac OS run has the Unverified HTTPS request warning, my script is identical on both machines.  I'm thinking it has something to do with the different requests version.)

$ query_rally.py  --credentialsFromFile PB9225
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./query_rally.py", line 371, in <module>
    main(sys.argv[1:])
  File "./query_rally.py", line 347, in main
    myQueryRally.setRallyObject()
  File "./query_rally.py", line 137, in setRallyObject
    verify_ssl_cert=self.verify_ssl_cert)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyral/restapi.py", line 227, in __init__
    self.contextHelper.check(self.server)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyral/context.py", line 220, in check
    self._getDefaults(response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyral/context.py", line 259, in _getDefaults
    user = response.next()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyral/rallyresp.py", line 256, in next
    raise StopIteration
StopIteration

Linux traceback

$ query_rally.py  --credentialsFromFile PB9225
Traceback (most recent call last):
  File "query_rally.py", line 371, in <module>
    main(sys.argv[1:])
  File "query_rally.py", line 347, in main
    myQueryRally.setRallyObject()
  File "query_rally.py", line 137, in setRallyObject
    verify_ssl_cert=self.verify_ssl_cert)
  File "/ascldap/users/aalorbe/trac/easy_install_files/2.6/site_packages/pyral-1.1.0-py2.6.egg/pyral/restapi.py", line 227, in __init__
    self.contextHelper.check(self.server)
  File "/ascldap/users/aalorbe/trac/easy_install_files/2.6/site_packages/pyral-1.1.0-py2.6.egg/pyral/context.py", line 220, in check
    self._getDefaults(response)
  File "/ascldap/users/aalorbe/trac/easy_install_files/2.6/site_packages/pyral-1.1.0-py2.6.egg/pyral/context.py", line 259, in _getDefaults
    user = response.next()
  File "/ascldap/users/aalorbe/trac/easy_install_files/2.6/site_packages/pyral-1.1.0-py2.6.egg/pyral/rallyresp.py", line 256, in next
    raise StopIteration
StopIteration

**Comment by klehman-rally** [comment]
incorporated user contributed code in 1.1.1
